DROP TABLE IF EXISTS TENNIS_UNIVERSE.PERSON_ACCOUNT;

CREATE TABLE IF NOT EXISTS TENNIS_UNIVERSE.PERSON_ACCOUNT
(
  ACCOUNT_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PERSON_ID INT (11),
  FOREIGN KEY (PERSON_ID)
  REFERENCES PERSON(PERSON_ID)
    ON DELETE CASCADE,
  ACCOUNT_TYPE INT(3),
  FOREIGN KEY (ACCOUNT_TYPE)
  REFERENCES ACCOUNT(ACCOUNT_TYPE)
    ON DELETE CASCADE,
  EFF_DATE DATE,
  EXP_DATE DATE,
  NOTES VARCHAR(100)
)ENGINE=InnoDB;
