DROP TABLE TENNIS_UNIVERSE.ADMIN_ACTION;

CREATE TABLE TENNIS_UNIVERSE.ADMIN_ACTION
(
  ADMIN_ACTION_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ACTION_DESC VARCHAR(30),
  ACTION_SERVLET_NAME VARCHAR(30)
)ENGINE=InnoDB;

INSERT INTO ADMIN_ACTION VALUES (10, 'ADD A NEW MEMBER', '/AddMemberDispServlet');
INSERT INTO ADMIN_ACTION VALUES (20, 'UPDATE MEMBER INFORMATION', '/UpdateMemberDispServlet');
INSERT INTO ADMIN_ACTION VALUES (30, 'ADD MEMBER SERVICES', '/AddMemeberServDispServlet');
INSERT INTO ADMIN_ACTION VALUES (40, 'PRINT MONTHLY MEMBER STATEMENT', '/PrintStatementDispServlet');
