CREATE TABLE TENNIS_UNIVERSE.ADMIN_ACTION
(
  ADMIN_ACTION_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ACTION_DESC VARCHAR(30)
)ENGINE=InnoDB;

INSERT INTO ADMIN_ACTION VALUES (10, 'ADD A NEW MEMBER');
INSERT INTO ADMIN_ACTION VALUES (20, 'UPDATE MEMBER INFORMATION');
INSERT INTO ADMIN_ACTION VALUES (30, 'ADD MEMBER SERVICES');
INSERT INTO ADMIN_ACTION VALUES (40, 'PRINT MONTHLY MEMBER STATEMENT');
