CREATE TABLE TENNIS_UNIVERSE.ACCOUNT
(
  ACCOUNT_TYPE INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_DESC VARCHAR(30),
  MONTHLY_CHARGE DECIMAL (5,2)
)ENGINE=InnoDB;

INSERT INTO ACCOUNT VALUES (10, 'FAMILY TENNIS', 350.00);
INSERT INTO ACCOUNT VALUES (20, 'COUPLE TENNIS',250.00);
INSERT INTO ACCOUNT VALUES (30, 'JUNIOR TENNIS',150.00);
INSERT INTO ACCOUNT VALUES (40, 'FITNESS', 50.00);