DROP TABLE IF EXISTS TENNIS_UNIVERSE.PERSON_ACCOUNT;
DROP TABLE IF EXISTS TENNIS_UNIVERSE.PERSON_SERVICE;
DROP TABLE IF EXISTS TENNIS_UNIVERSE.PERSON;

create table IF NOT EXISTS PERSON (
  PERSON_ID       int(11) NOT NULL auto_increment PRIMARY KEY ,
  SSN_NR          INT(09),
  FIRST_NAME      varchar(35) NOT NULL,
  LAST_NAME       varchar(35) NOT NULL ,
  BIRTH_DT        DATE,
  PERSON_TYPE     INT(02) NOT NULL ,
  EMAIL_ADDR      varchar(45),
  ADDRESS_LINE1   varchar(45),
  ADDRESS_LINE2   varchar(45),
  CITY            varchar(45),
  STATE           varchar(02),
  ZIP             varchar(05),
  PHONE           VARCHAR(10),
  LAST_UPDATED    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE=InnoDB;

INSERT INTO PERSON VALUES (101, 999999999, "JOE", "COYNE", "1969-03-04", 02, "JCOYNE@GMAIL.COM", "1 MAIN ST","" , "MADISON", "WI", "53555", "6089997755", CURRENT_TIMESTAMP);
INSERT INTO PERSON VALUES (102, 999999999, "LENA", "COYNE", "1973-03-04", 02, "LCOYNE@GMAIL.COM", "1 MAIN ST","" , "MADISON", "WI", "53555", "6083454400", CURRENT_TIMESTAMP);
INSERT INTO PERSON VALUES (103, 999999999, "KRISTI", "COYNE", "1993-03-04", 02, "KCOYNE@GMAIL.COM", "1 MAIN ST","" , "MADISON", "WI", "53555", "6083456868", CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS TENNIS_UNIVERSE.PERSON_ACCOUNT
(
  ACCOUNT_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PERSON_ID INT (11),
  FOREIGN KEY (PERSON_ID)
  REFERENCES PERSON(PERSON_ID)
    ON DELETE CASCADE,
  ACCOUNT_TYPE INT(3),
  FOREIGN KEY (ACCOUNT_TYPE)
  REFERENCES ACCOUNT(ACCOUNT_TYPE)
    ON DELETE CASCADE,
  EFF_DATE DATE,
  EXP_DATE DATE,
  NOTES VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TENNIS_UNIVERSE.PERSON_SERVICE
(
  PERSON_SERVICE_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PERSON_ID INT (11) NOT NULL ,
  FOREIGN KEY (PERSON_ID)
  REFERENCES PERSON(PERSON_ID)
    ON DELETE CASCADE,
  SERVICE_ID INT(3) NOT NULL ,
  FOREIGN KEY (SERVICE_ID)
  REFERENCES SERVICE(SERVICE_ID)
    ON DELETE CASCADE,
  SERVICE_DATE DATE NOT NULL ,
  NOTES VARCHAR(100)
)ENGINE=InnoDB;

