CREATE TABLE ACCOUNT
(
    ACCOUNT_TYPE INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ACCOUNT_DESC VARCHAR(30),
    MONTHLY_CHARGE DECIMAL(5,2)
);
CREATE TABLE ADMIN_ACTION
(
    ADMIN_ACTION_ID INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ACTION_DESC VARCHAR(30),
    ACTION_SERVLET_NAME VARCHAR(30)
);
CREATE TABLE PERSON
(
    PERSON_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SSN_NR INT(9),
    FIRST_NAME VARCHAR(35) NOT NULL,
    LAST_NAME VARCHAR(35) NOT NULL,
    BIRTH_DT DATE,
    PERSON_TYPE INT(2) NOT NULL,
    EMAIL_ADDR VARCHAR(45),
    ADDRESS_LINE1 VARCHAR(45),
    ADDRESS_LINE2 VARCHAR(45),
    CITY VARCHAR(45),
    STATE VARCHAR(2),
    ZIP VARCHAR(5),
    PHONE VARCHAR(10),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE PERSON_ACCOUNT
(
    ACCOUNT_ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PERSON_ID INT(11),
    ACCOUNT_TYPE INT(3),
    EFF_DATE DATE,
    EXP_DATE DATE,
    NOTES VARCHAR(100),
    CONSTRAINT PERSON_ACCOUNT_ibfk_1 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT PERSON_ACCOUNT_ibfk_2 FOREIGN KEY (ACCOUNT_TYPE) REFERENCES ACCOUNT (ACCOUNT_TYPE) ON DELETE CASCADE
);
CREATE INDEX ACCOUNT_TYPE ON PERSON_ACCOUNT (ACCOUNT_TYPE);
CREATE INDEX PERSON_ID ON PERSON_ACCOUNT (PERSON_ID);
CREATE TABLE PERSON_SERVICE
(
    PERSON_SERVICE_ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PERSON_ID INT(11) NOT NULL,
    SERVICE_ID INT(3) NOT NULL,
    SERVICE_DATE DATE NOT NULL,
    NOTES VARCHAR(100),
    CONSTRAINT PERSON_SERVICE_ibfk_1 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT PERSON_SERVICE_ibfk_2 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (SERVICE_ID) ON DELETE CASCADE
);
CREATE INDEX PERSON_ID ON PERSON_SERVICE (PERSON_ID);
CREATE INDEX SERVICE_ID ON PERSON_SERVICE (SERVICE_ID);
CREATE TABLE SERVICE
(
    SERVICE_ID INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SERVICE_CODE VARCHAR(2) NOT NULL,
    SERVICE_DESC VARCHAR(35) NOT NULL,
    SERVICE_CHARGE DECIMAL(9,2) NOT NULL
);
CREATE TABLE USER
(
    USER_ID INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(15) NOT NULL,
    USER_PASS VARCHAR(15) NOT NULL
);
CREATE TABLE USER_ROLE
(
    USER_ROLES_ID INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(15) NOT NULL,
    ROLE_NAME VARCHAR(15) NOT NULL
);